### ISSUE TITLE
MPS metadata folder is missing

### ISSUE THREAD

**Issue by kbirken** [IlyaYuskevich/ModelBasedTrm#1]
The project cannot be opened with MPS.

The `.mps` folder seems to be missing, which is required to load the project in MPS. It would also be helpful to specify which MPS has to be used (2020.3, 2021.1, and so on).

**Comment by IlyaYuskevich** [comment]
Thanks! Commit 9f153c64c4948aa3834ef4b9f31261706ec896d1 should fix the issue.
